### PR TITLE
More significant warning fixes

### LINKED ISSUE #17: More significant warnings on CRAN R-devel
After submitting to CRAN, it came up with more significant warnings on one platform:

```
* using log directory ‘/srv/hornik/tmp/CRAN/Rttf2pt1.Rcheck’
* using R Under development (unstable) (2022-10-05 r83033)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘Rttf2pt1/DESCRIPTION’ ... OK
* this is package ‘Rttf2pt1’ version ‘1.3.11’
* package encoding: UTF-8
* checking CRAN incoming feasibility ... [2s/2s] NOTE
Maintainer: ‘Winston Chang <winston@stdout.org>’

CRAN repository db overrides:
  License_is_FOSS: yes
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘Rttf2pt1’ can be installed ... [5s/5s] WARNING
Found the following significant warnings:
  ttf2pt1.c:659:41: warning: format ‘%i’ expects argument of type ‘int *’, but argument 3 has type ‘unsigned int *’ [-Wformat=]
  ttf2pt1.c:688:47: warning: format ‘%i’ expects argument of type ‘int *’, but argument 3 has type ‘unsigned int *’ [-Wformat=]
  ttf2pt1.c:703:67: warning: format ‘%i’ expects argument of type ‘int *’, but argument 3 has type ‘unsigned int *’ [-Wformat=]
  ttf2pt1.c:720:48: warning: format ‘%i’ expects argument of type ‘int *’, but argument 3 has type ‘unsigned int *’ [-Wformat=]
  ttf2pt1.c:1081:36: warning: format ‘%d’ expects argument of type ‘int *’, but argument 3 has type ‘unsigned int *’ [-Wformat=]
  t1asm.c:173:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  t1asm.c:250:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  t1asm.c:270:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  t1asm.c:295:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  t1asm.c:309:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  t1asm.c:357:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  t1asm.c:384:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  t1asm.c:428:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  t1asm.c:463:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
  t1asm.c:476:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
See ‘/srv/hornik/tmp/CRAN/Rttf2pt1.Rcheck/00install.out’ for details.
```

### PR DESCRIPTION
**Pull request by wch**
This fixes #17.

### CODE REVIEW

File: src/ttf2pt1/ttf2pt1.c [hunk 1]
```diff
@@ -656,7 +656,7 @@ unicode_init_user(
 		if( !enabled )
 			continue; /* skip to the next plane */
 
-		if( sscanf(buffer, "at %i", &curpos) == 1 ) {
```
Comment (wch) [inline src/ttf2pt1/ttf2pt1.c:659]: This may look a bit odd, casting the pointer to an `int*`. It's done because I'm not sure if it's safe to convert `%i` to, say, `%u`.

It would be safe to change from `%d` to `%u`, because those both operate on strings of decimal digits. However, `%i` can accepts decimal hexadecimal, and octal digits. I don't know if the actual input has hexadecimal or octal digits, so it seemed safer to simply cast the pointer, especially since the code has worked fine for all these years.
